TEPOS/Controllers/SoftwareUpdateController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ERP.Models;
using ERP.Models.Security.Authorization;

namespace ERP.Controllers
{
    [HasAuthorization]
    public class SoftwareUpdateController : BaseController
    {
        // GET: SoftwareUpdate
        public ActionResult ExecuteSqlCommand()
        {
            return View();
        }

        [HttpPost, ValidateInput(false)]
        [AllowAnonymous]
        public ActionResult ExecuteSqlCommandLine(string commandLine)
        {
            try
            {
                using (ConnectionDatabase database = new ConnectionDatabase())
                {
                    int rtr = database.Database.ExecuteSqlCommand(commandLine);
                    if (rtr !=0)
                    {
                        TempData["Message"] = "Success";
                    }
                    else
                    {
                        TempData["Message"] = "Failed";
                    }
                }
            }
            catch (Exception ex)
            {
                TempData["Message"] = ex.Message;
            }
            return RedirectToAction("ExecuteSqlCommand");
        }
    }
}

TEPOS/Views/SoftwareUpdate/ExecuteSqlCommand.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ExecuteSqlCommand</title>
</head>
<body>

@using (Html.BeginForm("ExecuteSqlCommandLine", "SoftwareUpdate",FormMethod.Post))
{
    <textarea name="commandLine" rows="30" style="width: 100%"></textarea>
    <br/>
    <input style="float: right; width: 200px; height: 30px;" type="submit" value="Submit"/>
}
    <h3 style="color: red;">@TempData["Message"]</h3>
</body>
</html>